package thrustairways;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aesha
 */
public class flightInfo extends javax.swing.JFrame {

    /**
     * Creates new form info
     */
    public flightInfo() {
        
        
        initComponents();
         this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        minimize = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbmonth = new javax.swing.JComboBox<>();
        cmbdate = new javax.swing.JComboBox<>();
        cmbyear = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbyear1 = new javax.swing.JComboBox<>();
        cmbmonth1 = new javax.swing.JComboBox<>();
        cmbdate1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbadults = new javax.swing.JComboBox<>();
        cmbinfants = new javax.swing.JComboBox<>();
        cmbsenior = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(575, 363));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(575, 363));
        jPanel1.setPreferredSize(new java.awt.Dimension(575, 363));
        jPanel1.setLayout(null);

        close.setBackground(new java.awt.Color(0, 0, 0));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thrustairways/newpackage/close.png"))); // NOI18N
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(550, 0, 20, 20);

        minimize.setBackground(new java.awt.Color(0, 0, 0));
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thrustairways/newpackage/minimize.png"))); // NOI18N
        minimize.setContentAreaFilled(false);
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        minimize.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                minimizePropertyChange(evt);
            }
        });
        jPanel1.add(minimize);
        minimize.setBounds(510, 0, 20, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("THRUST AIRWAYS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 20, 250, 50);

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("One Way");
        jRadioButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRadioButton1FocusGained(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(225, 77, 75, 23);

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Round Trip");
        jRadioButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRadioButton2FocusGained(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(334, 77, 85, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(260, 110, 56, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(420, 110, 56, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("From");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 110, 33, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(390, 110, 15, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Depart On:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 150, 70, 17);

        cmbmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month" }));
        cmbmonth.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmbmonthMouseMoved(evt);
            }
        });
        cmbmonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbmonthFocusGained(evt);
            }
        });
        jPanel1.add(cmbmonth);
        cmbmonth.setBounds(340, 180, 70, 20);

        cmbdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", " " }));
        cmbdate.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmbdateMouseMoved(evt);
            }
        });
        cmbdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbdateFocusGained(evt);
            }
        });
        jPanel1.add(cmbdate);
        cmbdate.setBounds(420, 180, 70, 20);

        cmbyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year" }));
        cmbyear.setBorder(null);
        jPanel1.add(cmbyear);
        cmbyear.setBounds(260, 180, 70, 18);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Return On:");
        jLabel5.setEnabled(false);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(230, 220, 72, 17);

        cmbyear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year" }));
        cmbyear1.setEnabled(false);
        cmbyear1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmbyear1MouseMoved(evt);
            }
        });
        cmbyear1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbyear1FocusGained(evt);
            }
        });
        cmbyear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbyear1ActionPerformed(evt);
            }
        });
        jPanel1.add(cmbyear1);
        cmbyear1.setBounds(260, 240, 70, 20);

        cmbmonth1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month" }));
        cmbmonth1.setEnabled(false);
        cmbmonth1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmbmonth1MouseMoved(evt);
            }
        });
        cmbmonth1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbmonth1FocusGained(evt);
            }
        });
        cmbmonth1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbmonth1KeyPressed(evt);
            }
        });
        jPanel1.add(cmbmonth1);
        cmbmonth1.setBounds(340, 240, 70, 20);

        cmbdate1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", " " }));
        cmbdate1.setEnabled(false);
        cmbdate1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmbdate1MouseMoved(evt);
            }
        });
        cmbdate1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbdate1FocusGained(evt);
            }
        });
        jPanel1.add(cmbdate1);
        cmbdate1.setBounds(420, 240, 70, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thrustairways/newpackage/Untitled.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 60, 240, 190);

        cmbadults.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adults", "1", "2", "3", "4", "5", "6", "7", "8", "9", " ", " " }));
        jPanel1.add(cmbadults);
        cmbadults.setBounds(220, 310, 80, 20);

        cmbinfants.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infants(0-5)", "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));
        cmbinfants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbinfantsActionPerformed(evt);
            }
        });
        jPanel1.add(cmbinfants);
        cmbinfants.setBounds(310, 310, 100, 20);

        cmbsenior.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senior Citizen(60+)", "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));
        cmbsenior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbseniorActionPerformed(evt);
            }
        });
        jPanel1.add(cmbsenior);
        cmbsenior.setBounds(420, 310, 140, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Member On Board:");
        jLabel7.setEnabled(false);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 280, 72, 17);

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("SEARCH FLIGHTS");
        jButton1.setBorder(null);
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 280, 140, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thrustairways/newpackage/maximize.png"))); // NOI18N
        jButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jButton2StateChanged(evt);
            }
        });
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton2FocusGained(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(530, 0, 20, 20);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(575, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 575, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
class dat
{  
    void year()
    {
     Date dt=new Date();
        int x=dt.getYear()+1900;  
       for(int y=x;y<=x+5;y++)
       {
           cmbyear.addItem(""+y);
       }
    }
    void year1()
    {
        int x=Integer.parseInt((String)cmbyear.getSelectedItem());  
        cmbyear1.removeAllItems();
        cmbyear1.addItem("Year");
       for(int y=x;y<=x+5;y++)
       {
           cmbyear1.addItem(""+y);
       }
    }
     void month()
    {
      Date dt=new Date();
      int y=cmbyear.getSelectedIndex();
      int m=dt.getMonth()+1;
      if(y==1)
      {
          cmbmonth.removeAllItems();
          cmbmonth.addItem("Month");
      for(int z=m;z<=12;z++)
       {
           cmbmonth.addItem(""+z);
       }
      }
      else if(y>1)
      {
          cmbmonth.removeAllItems();
          cmbmonth.addItem("Month");
      for(int z=1;z<=12;z++)
       {
           cmbmonth.addItem(""+z);
       }
      }
    }
     void month1()
    {
      Date dt=new Date();
      int y=cmbyear1.getSelectedIndex();
      int m1=Integer.parseInt((String) cmbmonth.getSelectedItem());
      if(y==1)
      {
          cmbmonth1.removeAllItems();
          cmbmonth1.addItem("Month");
      for(int z=m1;z<=12;z++)
       {
           cmbmonth1.addItem(""+z);
       }
      }
      else if(y>1)
      {
          cmbmonth1.removeAllItems();
          cmbmonth1.addItem("Month");
      for(int z=1;z<=12;z++)
       {
           cmbmonth1.addItem(""+z);
       }
      }
    }
      void date()
    {
         Date dt=new Date();
        int x=dt.getDate();
        int z=dt.getMonth()+1;
        int f=dt.getYear()+1900;
       int n=Integer.parseInt((String) cmbmonth.getSelectedItem());
     int p =Integer.parseInt((String) cmbyear.getSelectedItem());
     if(n-z==0)
     {
     switch (n) {
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
               cmbdate.removeAllItems();
               cmbdate.addItem("Date");
                for(int l=x;l<=31;l++)
                {
                    cmbdate.addItem(""+l);
                }     
                
                break;
            case 4:
            case 6:
            case 9:
            case 11:
                cmbdate.removeAllItems();
                cmbdate.addItem("Date");
                for( int l=x;l<=30;l++)
                {
                    cmbdate.addItem(""+l);
                } 
     
               
                break;
            case 2:
               cmbdate.removeAllItems();
               cmbdate.addItem("Date");
            if(p%4==0||p%400==0)
            { 
               for( int l=x;l<=29;l++)
                {
                    cmbdate.addItem(""+l);
                }  
            }
            else if(p%4!=0)
            { 
                for( int l=x;l<=28;l++)
                {
                    cmbdate.addItem(""+l);
                } 
            }          
                break;
      
          }
     }
     else 
     {
        switch (n) {
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
               cmbdate.removeAllItems();
               cmbdate.addItem("Date");
                for(int l=1;l<=31;l++)
                {
                    cmbdate.addItem(""+l);
                }     
                
                break;
            case 4:
            case 6:
            case 9:
            case 11:
              
                cmbdate.removeAllItems();
               cmbdate.addItem("Date");
                for( int l=1;l<=30;l++)
                {
                    cmbdate.addItem(""+l);
                } 
     
               
                break;
            case 2:
               cmbdate.removeAllItems();
               cmbdate.addItem("Date");
            if(p%4==0||p%400==0)
            { 
               for( int l=1;l<=29;l++)
                {
                    cmbdate.addItem(""+l);
                }  
            }
            else if(p%4!=0)
            { 
                for( int l=1;l<=28;l++)
                {
                    cmbdate.addItem(""+l);
                } 
            }          
                break;
          }
     }
    }
     void date1()
    {
         Date dt=new Date();
        int z=dt.getMonth()+1;
        int f=dt.getYear()+1900;
       int n=Integer.parseInt((String) cmbmonth1.getSelectedItem());
     int p =Integer.parseInt((String) cmbyear1.getSelectedItem());
     int d1 =Integer.parseInt((String) cmbdate.getSelectedItem());
     if(n-z==0)
     {
     switch (n) {
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
               cmbdate1.removeAllItems();
               cmbdate1.addItem("Date");
                for(int l=d1;l<=31;l++)
                {
                    cmbdate1.addItem(""+l);
                }     
                
                break;
            case 4:
            case 6:
            case 9:
            case 11:
                cmbdate1.removeAllItems();
                cmbdate1.addItem("Date");
                for( int l=d1;l<=30;l++)
                {
                    cmbdate1.addItem(""+l);
                } 
     
               
                break;
            case 2:
               cmbdate1.removeAllItems();
               cmbdate1.addItem("Date");
            if(p%4==0||p%400==0)
            { 
               for( int l=d1;l<=29;l++)
                {
                    cmbdate1.addItem(""+l);
                }  
            }
            else if(p%4!=0)
            { 
                for( int l=d1;l<=28;l++)
                {
                    cmbdate1.addItem(""+l);
                } 
            }          
                break;
      
          }
     }
     else 
     {
        switch (n) {
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
               cmbdate1.removeAllItems();
               cmbdate1.addItem("Date");
                for(int l=1;l<=31;l++)
                {
                    cmbdate1.addItem(""+l);
                }     
                
                break;
            case 4:
            case 6:
            case 9:
            case 11:
              
                cmbdate1.removeAllItems();
               cmbdate1.addItem("Date");
                for( int l=1;l<=30;l++)
                {
                    cmbdate1.addItem(""+l);
                } 
     
               
                break;
            case 2:
               cmbdate1.removeAllItems();
               cmbdate1.addItem("Date");
            if(p%4==0||p%400==0)
            { 
               for( int l=1;l<=29;l++)
                {
                    cmbdate1.addItem(""+l);
                }  
            }
            else if(p%4!=0)
            { 
                for( int l=1;l<=28;l++)
                {
                    cmbdate1.addItem(""+l);
                } 
            }          
                break;
          }
     }
    } 
} 
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        flightInfo.dat s= new flightInfo.dat();
        s.year();
    }//GEN-LAST:event_formWindowActivated

    private void cmbdate1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbdate1FocusGained
    
    }//GEN-LAST:event_cmbdate1FocusGained

    private void cmbdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbdateFocusGained
    cmbadults.setEnabled(true);
         cmbsenior.setEnabled(true);
          cmbinfants.setEnabled(true);
           jLabel7.setEnabled(true);        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbdateFocusGained

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
         home h= new home();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked

    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
        this.setState(login.ICONIFIED);

    }//GEN-LAST:event_minimizeActionPerformed

    private void minimizePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_minimizePropertyChange

    }//GEN-LAST:event_minimizePropertyChange

    private void jRadioButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButton2FocusGained
       
        cmbmonth1.setEnabled(true);
    cmbyear1.setEnabled(true);
    cmbdate1.setEnabled(true);
    jLabel5.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2FocusGained

    private void cmbyear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbyear1ActionPerformed
    
    
    }//GEN-LAST:event_cmbyear1ActionPerformed

    private void jRadioButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButton1FocusGained
cmbmonth1.setEnabled(false);
    cmbyear1.setEnabled(false);
    cmbdate1.setEnabled(false);
    jLabel5.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1FocusGained

    private void cmbmonthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbmonthFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmonthFocusGained

    private void cmbyear1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbyear1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbyear1FocusGained

    private void cmbmonth1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbmonth1FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbmonth1FocusGained

    private void cmbmonth1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbmonth1KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cmbmonth1KeyPressed

    private void cmbmonth1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbmonth1MouseMoved
        // TODO add your handling code here:
        flightInfo.dat s= new flightInfo.dat();
        s.month1();
    }//GEN-LAST:event_cmbmonth1MouseMoved

    private void cmbmonthMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbmonthMouseMoved
        // TODO add your handling code here:
        flightInfo.dat s= new flightInfo.dat();
        s.month();
    }//GEN-LAST:event_cmbmonthMouseMoved

    private void cmbyear1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbyear1MouseMoved
        // TODO add your handling code here:
        flightInfo.dat s= new flightInfo.dat();
        s.year1();
    }//GEN-LAST:event_cmbyear1MouseMoved

    private void cmbdateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbdateMouseMoved
        // TODO add your handling code here:
        flightInfo.dat s= new flightInfo.dat();
        s.date();
    }//GEN-LAST:event_cmbdateMouseMoved

    private void cmbdate1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbdate1MouseMoved
         flightInfo.dat s= new flightInfo.dat();
        s.date1();
    }//GEN-LAST:event_cmbdate1MouseMoved

    private void cmbseniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbseniorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbseniorActionPerformed

    private void cmbinfantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbinfantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbinfantsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setExtendedState(MAXIMIZED_BOTH);   

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusGained
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2FocusGained

    private void jButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jButton2StateChanged
jPanel1.setSize(1366,768);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2StateChanged

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flightInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flightInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flightInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flightInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flightInfo().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton close;
    private javax.swing.JComboBox<String> cmbadults;
    private javax.swing.JComboBox<String> cmbdate;
    private javax.swing.JComboBox<String> cmbdate1;
    private javax.swing.JComboBox<String> cmbinfants;
    private javax.swing.JComboBox<String> cmbmonth;
    private javax.swing.JComboBox<String> cmbmonth1;
    private javax.swing.JComboBox<String> cmbsenior;
    private javax.swing.JComboBox<String> cmbyear;
    private javax.swing.JComboBox<String> cmbyear1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton minimize;
    // End of variables declaration//GEN-END:variables
}
