
package thrustairways;

import java.awt.Color;

/**
 *
 * @author Aesha
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        output = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        minimize = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        close = new javax.swing.JButton();
        signin = new javax.swing.JButton();
        txtpas = new javax.swing.JPasswordField();
        chb = new javax.swing.JCheckBox();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(null);

        output.setBackground(new java.awt.Color(0, 0, 0));
        output.setForeground(new java.awt.Color(255, 0, 0));
        output.setBorder(null);
        getContentPane().add(output);
        output.setBounds(320, 300, 240, 30);

        txtuser.setBackground(new java.awt.Color(0, 0, 0));
        txtuser.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        txtuser.setAlignmentX(0.1F);
        txtuser.setAlignmentY(0.1F);
        txtuser.setBorder(null);
        txtuser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        getContentPane().add(txtuser);
        txtuser.setBounds(340, 130, 130, 20);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 20);

        minimize.setBackground(new java.awt.Color(0, 0, 0));
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thrustairways/newpackage/minimize.png"))); // NOI18N
        minimize.setContentAreaFilled(false);
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        minimize.setNextFocusableComponent(minimize);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeActionPerformed(evt);
            }
        });
        minimize.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                minimizePropertyChange(evt);
            }
        });
        getContentPane().add(minimize);
        minimize.setBounds(530, 0, 20, 20);

        signup.setBackground(new java.awt.Color(0, 153, 255));
        signup.setText("SIGN UP");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup);
        signup.setBounds(430, 250, 80, 30);

        close.setBackground(new java.awt.Color(0, 0, 0));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thrustairways/newpackage/close.png"))); // NOI18N
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(550, 0, 20, 20);

        signin.setBackground(new java.awt.Color(0, 153, 255));
        signin.setText("LOG IN");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        getContentPane().add(signin);
        signin.setBounds(340, 250, 80, 30);

        txtpas.setBackground(new java.awt.Color(0, 0, 0));
        txtpas.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtpas.setForeground(new java.awt.Color(255, 255, 255));
        txtpas.setAlignmentX(0.1F);
        txtpas.setAlignmentY(0.1F);
        txtpas.setBorder(null);
        txtpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasActionPerformed(evt);
            }
        });
        getContentPane().add(txtpas);
        txtpas.setBounds(340, 184, 130, 20);

        chb.setBackground(new java.awt.Color(0, 0, 0));
        chb.setForeground(new java.awt.Color(255, 255, 255));
        chb.setText("show password");
        chb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbActionPerformed(evt);
            }
        });
        getContentPane().add(chb);
        chb.setBounds(340, 210, 140, 23);

        image.setBackground(new java.awt.Color(0, 0, 0));
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thrustairways/newpackage/login.jpg"))); // NOI18N
        image.setMaximumSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(image);
        image.setBounds(0, 0, 570, 360);

        setBounds(0, 0, 571, 356);
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void chbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbActionPerformed
if(chb.isSelected())
{
txtpas.setEchoChar((char)0);
}
else
{
    txtpas.setEchoChar('*');
}
    }//GEN-LAST:event_chbActionPerformed

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        String user=txtuser.getText();
        String pass=new String(txtpas.getPassword());
        if(pass.equals("angrybirds")&&user.equals("hi5daksh")||pass.equals("infinitywar")&&user.equals("ashwin10"))
        {
        output.setText("Logging in...");
        String u=output.getText();
         if (u.equals("Logging in..."))       
       {                                 
                    try
                    {
                        
                     Thread.sleep(2000);
                     home h=new home();
                     h.setVisible(true);
                     this.setVisible(false);
                    }
                    catch( InterruptedException e)
                    {
                    }
        }
        
        }
        else
        {
        output.setText("Please check your username or password");
        }
    }//GEN-LAST:event_signinActionPerformed

    private void txtpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeActionPerformed
this.setState(login.ICONIFIED); 
       
    }//GEN-LAST:event_minimizeActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
 
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_minimizePropertyChange
            
    }//GEN-LAST:event_minimizePropertyChange

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        
        SignUp s=new SignUp();
        this.setVisible(false);
        s.setVisible(true);
        
    }//GEN-LAST:event_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
      
        
      
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chb;
    private javax.swing.JButton close;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minimize;
    private javax.swing.JTextField output;
    private javax.swing.JButton signin;
    private javax.swing.JButton signup;
    private javax.swing.JPasswordField txtpas;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables

    private void setExtentedState(int HIDE_ON_CLOSE) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
